require 'rake/testtask'

task :default => [:run]

task :run do
    ruby "./lib/app.rb"
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end
